/*
 * =====================================================================
 *  AES symmetric encryption with the JCE                 Medium   MUST-KNOW
 * =====================================================================
 *
 * WHAT THIS DEMONSTRATES
 *   The four-object pipeline every Java encryption task uses: SecretKey ->
 *   Cipher -> doFinal -> Base64. It shows it twice: once the textbook way with
 *   Cipher.getInstance("AES"), which silently means ECB mode, and once the way
 *   you would actually ship, AES/GCM with a random IV and an auth tag. The same
 *   key encrypts and decrypts - that is what "symmetric" means.
 *
 * WHAT YOU WILL SEE
 *   ECB round trip  : "Hello AES!" -> Base64 ciphertext -> "Hello AES!"
 *   ECB determinism : encrypting the same text twice gives the SAME bytes (bad)
 *   GCM round trip  : "Hello AES!" -> Base64 ciphertext -> "Hello AES!"
 *   GCM randomness  : encrypting the same text twice gives DIFFERENT bytes (good)
 *   GCM tamper test : flipping one ciphertext byte makes decryption throw
 *
 * HOW IT WORKS
 *   1. SecretKeySpec wraps raw bytes as an AES key. AES accepts exactly 16, 24
 *      or 32 bytes (AES-128 / 192 / 256); 16 chars of ASCII is 16 bytes.
 *   2. Cipher.getInstance(transformation) picks algorithm/mode/padding. "AES"
 *      alone resolves to "AES/ECB/PKCS5Padding" - the mode is implied, not absent.
 *   3. init(ENCRYPT_MODE, key) then doFinal(bytes) produces the ciphertext.
 *   4. Ciphertext is raw bytes, not text, so Base64 encodes it for printing or
 *      for storing in a String column. Base64 is encoding, never encryption.
 *   5. init(DECRYPT_MODE, key) with the same key reverses it. For GCM the IV
 *      must be supplied again, so it is prepended to the ciphertext and split
 *      off before decrypting.
 *
 * KEY INSIGHT
 *   The mode of operation, not AES itself, decides whether the output leaks
 *   anything. ECB encrypts each 16-byte block independently, so equal plaintext
 *   blocks give equal ciphertext blocks and the structure of the data shows
 *   through. GCM mixes in a per-message IV and appends an authentication tag,
 *   so the same plaintext looks different every time and any tampering is
 *   detected on decrypt. "AES/GCM/NoPadding with a fresh random IV" is the
 *   answer to give; "Cipher.getInstance(\"AES\")" is the answer to recognise
 *   as a finding in a code review.
 *
 * GOTCHAS
 *   - Cipher.getInstance("AES") == ECB. Never ship it; it is the demo default.
 *   - A hardcoded key string in source is a leaked key. Real keys come from a
 *     KMS, a keystore, or KeyGenerator, and are rotated.
 *   - Never reuse an IV with the same GCM key; that breaks the mode outright.
 *   - plainText.getBytes() uses the platform charset. Always name UTF-8.
 *   - Cipher objects are stateful and NOT thread safe - do not share one.
 *   - GCM decrypt failure throws AEADBadTagException; catch it, do not ignore it.
 *
 * INTERVIEW FOLLOW-UPS
 *   - AES-GCM vs AES-CBC + HMAC: what does GCM give you for free?
 *   - Where does the key live in production, and how do you rotate it?
 *   - Encrypting a column so you can still search it - why is that hard?
 *   - Symmetric vs asymmetric: when do you need RSA instead? (see C01_RSA)
 *
 * RUN
 *   main() runs 5 cases (ECB round trip, ECB determinism, GCM round trip,
 *   GCM randomness, GCM tamper detection) and prints actual vs expected.
 */

import javax.crypto.Cipher;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import java.nio.charset.StandardCharsets;
import java.security.SecureRandom;
import java.util.Arrays;
import java.util.Base64;

class AESExample {

    // Demo only. A real key is generated by KeyGenerator and kept in a KMS.
    private static final byte[] KEY_BYTES = "1234567890123456".getBytes(StandardCharsets.UTF_8);
    private static final SecretKeySpec KEY = new SecretKeySpec(KEY_BYTES, "AES");

    private static final int GCM_IV_BYTES = 12;   // 96-bit IV is the GCM standard
    private static final int GCM_TAG_BITS = 128;  // full-length auth tag
    private static final SecureRandom RANDOM = new SecureRandom();

    // ---------------------------------------------------------------- ECB ---
    // The author's original pipeline, kept as-is so the flaw stays visible.

    static String encryptEcb(String plainText) throws Exception {
        Cipher cipher = Cipher.getInstance("AES"); // == AES/ECB/PKCS5Padding
        cipher.init(Cipher.ENCRYPT_MODE, KEY);
        byte[] encrypted = cipher.doFinal(plainText.getBytes(StandardCharsets.UTF_8));
        return Base64.getEncoder().encodeToString(encrypted);
    }

    static String decryptEcb(String base64CipherText) throws Exception {
        Cipher cipher = Cipher.getInstance("AES");
        cipher.init(Cipher.DECRYPT_MODE, KEY);
        byte[] decrypted = cipher.doFinal(Base64.getDecoder().decode(base64CipherText));
        return new String(decrypted, StandardCharsets.UTF_8);
    }

    // ---------------------------------------------------------------- GCM ---
    // What you would actually ship: random IV per message + authentication tag.

    static String encryptGcm(String plainText) throws Exception {
        byte[] iv = new byte[GCM_IV_BYTES];
        RANDOM.nextBytes(iv); // a fresh IV per message is mandatory for GCM

        Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
        cipher.init(Cipher.ENCRYPT_MODE, KEY, new GCMParameterSpec(GCM_TAG_BITS, iv));
        byte[] cipherText = cipher.doFinal(plainText.getBytes(StandardCharsets.UTF_8));

        // The IV is not secret, but the receiver needs it: ship it in front.
        byte[] ivAndCipherText = new byte[iv.length + cipherText.length];
        System.arraycopy(iv, 0, ivAndCipherText, 0, iv.length);
        System.arraycopy(cipherText, 0, ivAndCipherText, iv.length, cipherText.length);
        return Base64.getEncoder().encodeToString(ivAndCipherText);
    }

    static String decryptGcm(String base64IvAndCipherText) throws Exception {
        byte[] all = Base64.getDecoder().decode(base64IvAndCipherText);
        byte[] iv = Arrays.copyOfRange(all, 0, GCM_IV_BYTES);
        byte[] cipherText = Arrays.copyOfRange(all, GCM_IV_BYTES, all.length);

        Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
        cipher.init(Cipher.DECRYPT_MODE, KEY, new GCMParameterSpec(GCM_TAG_BITS, iv));
        // Throws AEADBadTagException if a single bit of iv or cipherText changed.
        return new String(cipher.doFinal(cipherText), StandardCharsets.UTF_8);
    }

    /** Flips one bit in the last byte so the GCM tag check must fail. */
    static String tamperWith(String base64Text) {
        byte[] all = Base64.getDecoder().decode(base64Text);
        all[all.length - 1] ^= 0x01;
        return Base64.getEncoder().encodeToString(all);
    }

    private static void print(String label, Object actual, Object expected) {
        System.out.println(label + ": " + actual + "   expected " + expected);
    }

    public static void main(String[] args) throws Exception {
        String plainText = "Hello AES!";

        // case 1: the classic round trip - same key both ways
        String ecb = encryptEcb(plainText);
        System.out.println("ECB ciphertext (Base64): " + ecb);
        print("case 1 ECB round trip ", decryptEcb(ecb), plainText);

        // case 2: ECB is deterministic - identical input, identical output.
        // That is the flaw: an observer can spot repeated values without the key.
        print("case 2 ECB repeats?   ", encryptEcb(plainText).equals(ecb), true);

        // case 3: GCM round trip, IV carried alongside the ciphertext
        String gcm = encryptGcm(plainText);
        System.out.println("GCM iv+ciphertext+tag (Base64): " + gcm);
        print("case 3 GCM round trip ", decryptGcm(gcm), plainText);

        // case 4: GCM is randomised - same plaintext, different ciphertext
        print("case 4 GCM repeats?   ", encryptGcm(plainText).equals(gcm), false);

        // case 5: edge - one flipped bit is caught by the auth tag, not ignored
        String verdict;
        try {
            decryptGcm(tamperWith(gcm));
            verdict = "no exception";
        } catch (javax.crypto.AEADBadTagException e) {
            verdict = "AEADBadTagException";
        }
        print("case 5 GCM tampered   ", verdict, "AEADBadTagException");
    }
}
